import { createFileRoute, Link } from "@tanstack/react-router";
import { AppShell } from "@/components/app-shell";
import { StatusBadge } from "@/components/status-badge";
import { isStaffRoles, useOverview } from "@/hooks/use-overview";
import { useLending } from "@/hooks/use-lending";
import { formatDate, formatMoney, humanise } from "@/lib/format";

export const Route = createFileRoute("/_authenticated/repayments")({
  head: () => ({
    meta: [
      { title: "Repayments — Credia" },
      { name: "description", content: "Track your Credia repayment schedule, next payment due and payment history." },
      { property: "og:title", content: "Repayments — Credia" },
      { property: "og:description", content: "Track your Credia repayment schedule and payment history." },
      { property: "og:type", content: "website" },
      { name: "twitter:card", content: "summary_large_image" },
    ],
  }),
  component: Repayments,
});

function Card({ children }: { children: React.ReactNode }) {
  return <div className="rounded-lg border border-border bg-card p-5">{children}</div>;
}

function Repayments() {
  const { data: session } = useOverview();
  const { data, isLoading } = useLending();

  const loans = data?.loans ?? [];
  const installments = data?.installments ?? [];
  const payments = (data?.payments ?? []).filter((p) => p.purpose === "loan_repayment");

  const next = installments.find((i) => ["upcoming", "due", "partially_paid", "late", "missed"].includes(i.status));

  return (
    <AppShell isStaff={isStaffRoles(session?.roles)} email={session?.profile?.email}>
      <div className="space-y-6">
        <div>
          <h1 className="font-serif text-2xl font-semibold tracking-tight">Repayments</h1>
          <p className="mt-1 text-sm text-muted-foreground">
            Your amortised schedule is generated by Credia at disbursement and never changes retroactively.
          </p>
        </div>

        {isLoading ? <p className="text-sm text-muted-foreground">Loading…</p> : null}

        {!isLoading && installments.length === 0 ? (
          <Card>
            <p className="text-sm text-muted-foreground">
              You have no repayment schedule yet. It appears once a loan is disbursed. See{" "}
              <Link to="/loans" className="text-primary underline">
                My loans
              </Link>
              .
            </p>
          </Card>
        ) : null}

        {next ? (
          <Card>
            <p className="text-sm text-muted-foreground">Next payment due</p>
            <p className="mt-1 font-serif text-2xl font-semibold">
              {formatMoney(
                Number(next.total_payment) - Number(next.amount_paid),
                loans.find((l) => l.id === next.loan_id)?.currency_code ?? "EUR",
              )}
            </p>
            <p className="mt-1 text-sm text-muted-foreground">
              Installment {next.installment_number} · due {formatDate(next.due_date)} · <StatusBadge status={next.status} />
            </p>
          </Card>
        ) : null}

        {loans.map((loan) => {
          const rows = installments.filter((i) => i.loan_id === loan.id);
          if (rows.length === 0) return null;
          return (
            <Card key={loan.id}>
              <div className="flex flex-wrap items-center justify-between gap-3">
                <p className="font-medium">
                  {loan.reference} · {humanise(loan.repayment_frequency)}
                </p>
                <StatusBadge status={loan.status} />
              </div>
              <div className="mt-4 overflow-x-auto rounded-md border border-border">
                <table className="w-full text-sm">
                  <thead className="bg-secondary/50 text-left">
                    <tr>
                      <th className="px-3 py-2">#</th>
                      <th className="px-3 py-2">Due date</th>
                      <th className="px-3 py-2">Payment</th>
                      <th className="px-3 py-2">Principal</th>
                      <th className="px-3 py-2">Interest</th>
                      <th className="px-3 py-2">Paid</th>
                      <th className="px-3 py-2">Status</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-border">
                    {rows.map((row) => (
                      <tr key={row.id}>
                        <td className="px-3 py-2">{row.installment_number}</td>
                        <td className="px-3 py-2">{formatDate(row.due_date)}</td>
                        <td className="px-3 py-2">{formatMoney(row.total_payment, loan.currency_code)}</td>
                        <td className="px-3 py-2">{formatMoney(row.principal_portion, loan.currency_code)}</td>
                        <td className="px-3 py-2">{formatMoney(row.interest_portion, loan.currency_code)}</td>
                        <td className="px-3 py-2">{formatMoney(row.amount_paid, loan.currency_code)}</td>
                        <td className="px-3 py-2">
                          <StatusBadge status={row.status} />
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </Card>
          );
        })}

        {payments.length > 0 ? (
          <Card>
            <h2 className="font-serif text-lg font-semibold">Payment history</h2>
            <ul className="mt-3 divide-y divide-border text-sm">
              {payments.map((payment) => (
                <li key={payment.id} className="flex flex-wrap items-center justify-between gap-2 py-2">
                  <span>
                    {payment.transaction_reference} · {humanise(payment.payment_method ?? "")}
                  </span>
                  <span className="flex items-center gap-3">
                    {formatMoney(payment.amount, payment.currency_code)}
                    <StatusBadge status={payment.status} />
                    <span className="text-xs text-muted-foreground">{formatDate(payment.created_at)}</span>
                  </span>
                </li>
              ))}
            </ul>
          </Card>
        ) : null}
      </div>
    </AppShell>
  );
}
