/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedGuaranteeRouteImport } from './routes/_authenticated/guarantee'
import { Route as AuthenticatedLoansRouteImport } from './routes/_authenticated/loans'
import { Route as AuthenticatedMyDocumentsRouteImport } from './routes/_authenticated/my-documents'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedRepaymentsRouteImport } from './routes/_authenticated/repayments'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminKycRouteImport } from './routes/_authenticated/admin/kyc'
import { Route as AuthenticatedAdminCustomersUserIdRouteImport } from './routes/_authenticated/admin/customers.$userId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGuaranteeRoute = AuthenticatedGuaranteeRouteImport.update({
  id: '/guarantee',
  path: '/guarantee',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLoansRoute = AuthenticatedLoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyDocumentsRoute =
  AuthenticatedMyDocumentsRouteImport.update({
    id: '/my-documents',
    path: '/my-documents',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRepaymentsRoute = AuthenticatedRepaymentsRouteImport.update({
  id: '/repayments',
  path: '/repayments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminKycRoute = AuthenticatedAdminKycRouteImport.update({
  id: '/admin/kyc',
  path: '/admin/kyc',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminCustomersUserIdRoute =
  AuthenticatedAdminCustomersUserIdRouteImport.update({
    id: '/admin/customers/$userId',
    path: '/admin/customers/$userId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/guarantee': typeof AuthenticatedGuaranteeRoute
  '/loans': typeof AuthenticatedLoansRoute
  '/my-documents': typeof AuthenticatedMyDocumentsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/repayments': typeof AuthenticatedRepaymentsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/admin/kyc': typeof AuthenticatedAdminKycRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/customers/$userId': typeof AuthenticatedAdminCustomersUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/guarantee': typeof AuthenticatedGuaranteeRoute
  '/loans': typeof AuthenticatedLoansRoute
  '/my-documents': typeof AuthenticatedMyDocumentsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/repayments': typeof AuthenticatedRepaymentsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/admin/kyc': typeof AuthenticatedAdminKycRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/customers/$userId': typeof AuthenticatedAdminCustomersUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/guarantee': typeof AuthenticatedGuaranteeRoute
  '/_authenticated/loans': typeof AuthenticatedLoansRoute
  '/_authenticated/my-documents': typeof AuthenticatedMyDocumentsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/repayments': typeof AuthenticatedRepaymentsRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/_authenticated/admin/kyc': typeof AuthenticatedAdminKycRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/customers/$userId': typeof AuthenticatedAdminCustomersUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/documents'
    | '/guarantee'
    | '/loans'
    | '/my-documents'
    | '/profile'
    | '/repayments'
    | '/support'
    | '/admin/kyc'
    | '/admin/'
    | '/admin/customers/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/documents'
    | '/guarantee'
    | '/loans'
    | '/my-documents'
    | '/profile'
    | '/repayments'
    | '/support'
    | '/admin/kyc'
    | '/admin'
    | '/admin/customers/$userId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/documents'
    | '/_authenticated/guarantee'
    | '/_authenticated/loans'
    | '/_authenticated/my-documents'
    | '/_authenticated/profile'
    | '/_authenticated/repayments'
    | '/_authenticated/support'
    | '/_authenticated/admin/kyc'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/customers/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/guarantee': {
      id: '/_authenticated/guarantee'
      path: '/guarantee'
      fullPath: '/guarantee'
      preLoaderRoute: typeof AuthenticatedGuaranteeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/loans': {
      id: '/_authenticated/loans'
      path: '/loans'
      fullPath: '/loans'
      preLoaderRoute: typeof AuthenticatedLoansRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-documents': {
      id: '/_authenticated/my-documents'
      path: '/my-documents'
      fullPath: '/my-documents'
      preLoaderRoute: typeof AuthenticatedMyDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/repayments': {
      id: '/_authenticated/repayments'
      path: '/repayments'
      fullPath: '/repayments'
      preLoaderRoute: typeof AuthenticatedRepaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/kyc': {
      id: '/_authenticated/admin/kyc'
      path: '/admin/kyc'
      fullPath: '/admin/kyc'
      preLoaderRoute: typeof AuthenticatedAdminKycRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/customers/$userId': {
      id: '/_authenticated/admin/customers/$userId'
      path: '/admin/customers/$userId'
      fullPath: '/admin/customers/$userId'
      preLoaderRoute: typeof AuthenticatedAdminCustomersUserIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedGuaranteeRoute: typeof AuthenticatedGuaranteeRoute
  AuthenticatedLoansRoute: typeof AuthenticatedLoansRoute
  AuthenticatedMyDocumentsRoute: typeof AuthenticatedMyDocumentsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRepaymentsRoute: typeof AuthenticatedRepaymentsRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
  AuthenticatedAdminKycRoute: typeof AuthenticatedAdminKycRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminCustomersUserIdRoute: typeof AuthenticatedAdminCustomersUserIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedGuaranteeRoute: AuthenticatedGuaranteeRoute,
  AuthenticatedLoansRoute: AuthenticatedLoansRoute,
  AuthenticatedMyDocumentsRoute: AuthenticatedMyDocumentsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRepaymentsRoute: AuthenticatedRepaymentsRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
  AuthenticatedAdminKycRoute: AuthenticatedAdminKycRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminCustomersUserIdRoute:
    AuthenticatedAdminCustomersUserIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
