-- Payment + guarantee status vocabulary for manual bank transfers
ALTER TYPE payment_status ADD VALUE IF NOT EXISTS 'declared';
ALTER TYPE payment_status ADD VALUE IF NOT EXISTS 'under_review';
ALTER TYPE payment_status ADD VALUE IF NOT EXISTS 'verified';
ALTER TYPE guarantee_status ADD VALUE IF NOT EXISTS 'eligible_for_refund';
ALTER TYPE guarantee_status ADD VALUE IF NOT EXISTS 'refund_pending';

-- Company bank accounts, per country + currency
CREATE TABLE IF NOT EXISTS public.bank_accounts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  country_id uuid REFERENCES public.countries(id) ON DELETE SET NULL,
  currency_code text NOT NULL REFERENCES public.currencies(code),
  label text,
  bank_name text NOT NULL,
  account_holder_name text NOT NULL,
  account_number text,
  iban text,
  bic_swift text,
  bank_address text,
  payment_instructions text NOT NULL DEFAULT '',
  payment_method text NOT NULL DEFAULT 'bank_transfer',
  display_order smallint NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

GRANT SELECT ON public.bank_accounts TO authenticated;
GRANT INSERT, UPDATE, DELETE ON public.bank_accounts TO authenticated;
GRANT ALL ON public.bank_accounts TO service_role;

ALTER TABLE public.bank_accounts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Customers can read active bank accounts"
  ON public.bank_accounts FOR SELECT TO authenticated
  USING (is_active = true OR public.is_staff(auth.uid()));

CREATE POLICY "Admins manage bank accounts"
  ON public.bank_accounts FOR ALL TO authenticated
  USING (public.has_role(auth.uid(), 'admin'))
  WITH CHECK (public.has_role(auth.uid(), 'admin'));

CREATE TRIGGER t_bank_accounts_updated BEFORE UPDATE ON public.bank_accounts
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- Bank transfer declaration + verification fields on payments
ALTER TABLE public.payments
  ADD COLUMN IF NOT EXISTS payment_reference text,
  ADD COLUMN IF NOT EXISTS bank_account_id uuid REFERENCES public.bank_accounts(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS guarantee_id uuid REFERENCES public.guarantees(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS declared_amount numeric,
  ADD COLUMN IF NOT EXISTS declared_currency text,
  ADD COLUMN IF NOT EXISTS transfer_date date,
  ADD COLUMN IF NOT EXISTS sender_name text,
  ADD COLUMN IF NOT EXISTS sender_bank_name text,
  ADD COLUMN IF NOT EXISTS bank_transaction_reference text,
  ADD COLUMN IF NOT EXISTS proof_file_path text,
  ADD COLUMN IF NOT EXISTS declared_at timestamptz,
  ADD COLUMN IF NOT EXISTS reviewed_at timestamptz,
  ADD COLUMN IF NOT EXISTS reviewed_by uuid REFERENCES auth.users(id),
  ADD COLUMN IF NOT EXISTS verified_at timestamptz,
  ADD COLUMN IF NOT EXISTS verified_by uuid REFERENCES auth.users(id),
  ADD COLUMN IF NOT EXISTS review_notes text,
  ADD COLUMN IF NOT EXISTS rejection_reason text,
  ADD COLUMN IF NOT EXISTS mismatch_flags text[] NOT NULL DEFAULT '{}';

CREATE INDEX IF NOT EXISTS idx_payments_payment_reference ON public.payments(payment_reference);
CREATE INDEX IF NOT EXISTS idx_payments_status ON public.payments(status);

-- Refund / release bookkeeping
ALTER TABLE public.guarantee_transactions
  ADD COLUMN IF NOT EXISTS destination_bank jsonb NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS completed_at timestamptz,
  ADD COLUMN IF NOT EXISTS payment_reference text;

-- Stable sequential numbers used to build human payment references
ALTER TABLE public.loans
  ADD COLUMN IF NOT EXISTS loan_number bigint GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE public.guarantees
  ADD COLUMN IF NOT EXISTS guarantee_number bigint GENERATED BY DEFAULT AS IDENTITY;